### PR TITLE
Multiplayer Refactor

### PR DESCRIPTION
**Pull request by RustyBamboo**
Good to merge! And dim35/CEN3031-Project-Server#8 needs to be merged

This introduces a framework for the server to control mob states

### CODE REVIEW

**Comment by AleksandrHovhannisyan** [comment]
Just two things I wanted to note:

- Removing `move_and_slide(velocity, UP_DIRECTION)` from `_physics_process(delta)` causes players to fall off ledges too sharply. This may actually be happening because `_physics_process(delta)` was removed from the Player and AnimatedEntity scenes.
- It looks like shift-running was accidentally removed

**Comment by RustyBamboo** [comment]
I'm not sure how to fix the gravity thing cause I've noticed that is_on_floor() will oscilate between true and false when on the floor so setting velocity.y to be 0 on the floor causes a flickering in the animations. But I changed the world entity loop to use _physics_process

**Comment by RustyBamboo** [comment]
I think we can merge this now as it's in a stable state. dim35/CEN3031-Project-Server#7 should also be merged

**Comment by AleksandrHovhannisyan** [comment]
Alright, cool! One additional thing I noticed is that the stamina depletes more quickly when attacking and walking than when attacking while stationary. Also, sprint running is quite fast, but I guess that's a minor thing we can tweak later.

**Comment by RustyBamboo** [comment]
Yeah, we'll have to figure out the stats for whatever classes we have

**Pull request merged**
