### PR TITLE
Spawners for players and mobs

### PR DESCRIPTION
**Pull request by mdwanner**

### CODE REVIEW

**Comment by RustyBamboo** [comment]
Looks good and it works! Do you think you can handle the merge conflicts?

**Comment by mdwanner** [comment]
Most conflicts should be fixed. Sorting out minor issues now to get it to run. Will have a commit soon.

**Comment by mdwanner** [comment]
Should be ready for merge now

**Comment by RustyBamboo** [comment]
Good work, merging!

**Pull request merged**
